version: '1'
services:
  keycloak:
    image: jboss/keycloak:latest
    ports:
      - 8080:8081
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
    command:
      - "-b 0.0.0.0"

  backend:
    image: ei-board_save:latest
    depends_on:
      keycloak:
        condition: service_healthy
